---
servers:
  - url: "http://localhost:8080"
openapi: "3.0.3"


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      name: Authorization
      bearerFormat: JWT  # Optional, arbitrary value for documentation purposes

  schemas:
    SubscriptionResponseMessage:
      $ref: './websocket-api.yaml#/components/schemas/SubscriptionResponseMessage'
    AccountSubscriptionMessage:
      $ref: './websocket-api.yaml#/components/schemas/AccountSubscriptionMessage'
    MarketSubscriptionMessage:
      $ref: './websocket-api.yaml#/components/schemas/MarketSubscriptionMessage'
    AccountStreamMessage:
      $ref: './websocket-api.yaml#/components/schemas/AccountStreamMessage'
    MarketStreamMessage:
      $ref: './websocket-api.yaml#/components/schemas/MarketStreamMessage'

paths:
  /auth/token:
    $ref: "./auth-api.yaml#/paths/~1auth~1token"
  /auth/v2/token:
    $ref: "./auth-api.yaml#/paths/~1auth~1v2~1token"
  /auth/jwks:
    $ref: "./auth-api.yaml#/paths/~1auth~1jwks"
  /auth/token/refresh:
    $ref: "./auth-api.yaml#/paths/~1auth~1token~1refresh"

  /api/v1/account:
    $ref: "./account-data-api.yaml#/paths/~1api~1v1~1account"
  /api/v1/account/fundingRateHistory:
    $ref: "./account-data-api.yaml#/paths/~1api~1v1~1account~1fundingRateHistory"
  /api/v1/account/preferences:
    $ref: "./account-data-api.yaml#/paths/~1api~1v1~1account~1preferences"
  /api/v1/account/transactions:
    $ref: "./account-data-api.yaml#/paths/~1api~1v1~1account~1transactions"
  /api/v1/account/trades:
    $ref: "./account-data-api.yaml#/paths/~1api~1v1~1account~1trades"

  /v1/exchange/depth:
    $ref: "./exchange-api.yaml#/paths/~1v1~1exchange~1depth"
  /v1/exchange/ticker:
    $ref: "./exchange-api.yaml#/paths/~1v1~1exchange~1ticker"
  /v1/exchange/tickers:
    $ref: "./exchange-api.yaml#/paths/~1v1~1exchange~1tickers"
  /v1/exchange/info:
    $ref: "./exchange-api.yaml#/paths/~1v1~1exchange~1info"
  /v1/exchange/trades:
    $ref: "./exchange-api.yaml#/paths/~1v1~1exchange~1trades"
  /v1/exchange/candlesticks:
    $ref: "./exchange-api.yaml#/paths/~1v1~1exchange~1candlesticks"
  /v1/exchange/fundingRateHistory:
    $ref: "./exchange-api.yaml#/paths/~1v1~1exchange~1fundingRateHistory"

  /api/v1/trade/leverage:
    $ref: "./trade-api.yaml#/paths/~1api~1v1~1trade~1leverage"
  /api/v1/trade/orders/cancel:
    $ref: "./trade-api.yaml#/paths/~1api~1v1~1trade~1orders~1cancel"
  /api/v1/trade/orders:
    $ref: "./trade-api.yaml#/paths/~1api~1v1~1trade~1orders"
  /api/v1/trade/openOrders:
    $ref: "./trade-api.yaml#/paths/~1api~1v1~1trade~1openOrders"
  /api/v1/trade/withdraw:
    $ref: "./trade-api.yaml#/paths/~1api~1v1~1trade~1withdraw"
  /api/v1/trade/accounts/authorize:
    $ref: "./trade-api.yaml#/paths/~1api~1v1~1trade~1accounts~1authorize"
  /api/v1/trade/accounts/deauthorize:
    $ref: "./trade-api.yaml#/paths/~1api~1v1~1trade~1accounts~1deauthorize"
  /api/v1/trade/adjustIsolatedMargin:
    $ref: "./trade-api.yaml#/paths/~1api~1v1~1trade~1adjustIsolatedMargin"

  /ws/account:
    $ref: "./websocket-api.yaml#/paths/~1ws~1account"
  /ws/market:
    $ref: "./websocket-api.yaml#/paths/~1ws~1market"

info:
  title: "Bluefin API"
  description: "Bluefin API"
  version: "1.0.0"
