openapi: 3.0.3
info:
  title: Bluefin API
  version: v1
  description: |
    All numeric quantities are represented as string in e9 format.
tags:
- name: Common Schemas
  description: "Common Schemas"
components:
  schemas:
    # enums
    OrderStatus:
      type: string
      description: "The current status of the order."
      enum:
      - OPEN
      - PARTIALLY_FILLED_OPEN
      - PARTIALLY_FILLED_CANCELED
      - FILLED
      - CANCELLED
      - EXPIRED
      - PARTIALLY_FILLED_EXPIRED
      - UNSPECIFIED
    OrderTimeInForce:
      type: string
      enum: [ GTT, IOC, FOK, UNSPECIFIED ]
      default: "GTT"
      description: |
        The time-in-force policy for the order. By default, all orders are GTT. UNSPECIFIED is set to default.
        
        GTT: Good Til Time
        
        IOC: Immediate Or Cancel
        
        FOK: Fill Or Kill    
    OrderType:
      type: string
      description: "The type of order."
      enum:
      - LIMIT
      - MARKET
      - STOP_LIMIT
      - STOP_MARKET
      - LIQUIDATION
      - BANKRUPTCY_LIQUIDATION
      - UNSPECIFIED

    # objects
    Asset:
      type: object
      description: "Details about an asset in the account."
      properties:
        symbol:
          type: string
          description: "The symbol of the asset."
        quantityE9:
          type: string
          description: "The quantity of the asset."
        effectiveBalanceE9:
          type: string
          description: "The effective balance of the asset."
        maxWithdrawQuantityE9:
          type: string
          description: "The maximum quantity that can be withdrawn."
        updatedAtMillis:
          type: integer
          format: int64
          description: "The timestamp of the last update in milliseconds."
      required:
      - symbol
      - quantityE9
      - effectiveBalanceE9
      - maxWithdrawQuantityE9
      - updatedAtMillis
    Error:
      type: object
      properties:
        errorCode:
          type: string
          description: A code representing the type of error.
        message:
          type: string
          description: A human-readable message describing the error.
      required:
      - message
    TradingFees:
      type: object
      required:
      - makerFeeE9
      - takerFeeE9
      - isApplied
      properties:
        makerFeeE9:
          type: string
          description: The Account Maker Fee (e9 format).
          example: "1000000"
        takerFeeE9:
          type: string
          description: The Account Taker Fee (e9 format).
          example: "1000000"
        isApplied:
          type: boolean
          description: Are the fees applied on the account?
