openapi: 3.0.3
info:
  title: Bluefin Exchange API
  description: Exchange Info Endpoints |
    All numeric quantities are represented as string in e9 format.
  version: 1.0.0

components:
  schemas:
    ExchangeInfoResponse:
      type: object
      properties:
        assets:
          type: array
          description: List of assets available on the exchange.
          items:
            $ref: "#/components/schemas/AssetConfig"
        contractsConfig:
          $ref: "#/components/schemas/ContractsConfig"
        markets:
          type: array
          description: List of markets available on the exchange.
          items:
            $ref: "#/components/schemas/Market"
        tradingGasFeeE9:
          type: string
          description: Current gas fee set for subsidized trades (e9 format)
        serverTimeAtMillis:
          type: integer
          format: int64
          description: Server time in milliseconds.
        timezone:
          type: string
          description: Timezone of the exchange.
      required:
        - assets
        - markets
        - tradingGasFeeE9
        - serverTimeAtMillis
        - timezone
    MarketStatus:
      type: string
      enum:
        - ACTIVE
        - BETA
        - MAINTENANCE
        - DELISTED
        - UNSPECIFIED
    ContractsConfig:
      type: object
      description: Contract configuration for the exchange.
      required:
        - edsId
        - idsId
        - network
        - baseContractAddress
        - currentContractAddress
        - operators
      properties:
        edsId:
          type: string
          example: "0x7c723c16bc4a4d3e1067360de6963cfdfbdc51a128563fe052cb4f8f00d6150b"
          description: External Data Store Address
        idsId:
          type: string
          example: "0x7c723c16bc4a4d3e1067360de6963cfdfbdc51a128563fe052cb4f8f00d6150b"
          description: External Data Store Address
        network:
          type: string
          enum: [mainnet, testnet, devnet]
          description: Network environment
        baseContractAddress:
          type: string
          example: "0xa6b939f57595fed2ae10ae4f3a37a410c94e5bdb7dde2e547022d1fe1b9791d0"
          description: Base contract address
        currentContractAddress:
          type: string
          example: "0xa6b939f57595fed2ae10ae4f3a37a410c94e5bdb7dde2e547022d1fe1b9791d0"
          description: Current contract address
        operators:
          $ref: "#/components/schemas/Operators"
    Operators:
      type: object
      required:
        - admin
        - operator
        - sequencer
        - funding
        - fee
      properties:
        admin:
          type: string
          description: Admin operator address
          example: "0xa6b939f57595fed2ae10ae4f3a37a410c94e5bdb7dde2e547022d1fe1b9791d0"
        operator:
          type: string
          description: General operator address; AKA Guardian
          deprecated: true
          example: "0xa6b939f57595fed2ae10ae4f3a37a410c94e5bdb7dde2e547022d1fe1b9791d0"
        sequencer:
          type: string
          description: Sequencer operator address
          example: "0xa6b939f57595fed2ae10ae4f3a37a410c94e5bdb7dde2e547022d1fe1b9791d0"
        funding:
          type: string
          description: Funding operator address
          deprecated: true
          example: "0xa6b939f57595fed2ae10ae4f3a37a410c94e5bdb7dde2e547022d1fe1b9791d0"
        fee:
          type: string
          description: Fee operator address
          deprecated: true
          example: "0xa6b939f57595fed2ae10ae4f3a37a410c94e5bdb7dde2e547022d1fe1b9791d0"
    AssetConfig:
      type: object
      properties:
        assetType:
          type: string
          description: The bank address of the asset.
        symbol:
          type: string
          description: Asset symbol.
          example: USDC
        decimals:
          type: integer
          format: int64
          description: Default precision for rendering this asset.
          example: 6
        weight:
          type: string
          description: Weight applied to asset to use as margin in Multi-Assets mode.
          example: 1.0
        marginAvailable:
          type: boolean
          description: Indicates if the asset can be used as margin in Multi-Assets mode.
      required:
        - assetType
        - symbol
        - decimals
        - weight
        - marginAvailable

    Market:
      type: object
      properties:
        symbol:
          type: string
          description: Symbol of the market.
          example: BTC-PERP
        marketAddress:
          type: string
          description: Market address.
          example: 0x123
        status:
          $ref: "#/components/schemas/MarketStatus"
        baseAssetSymbol:
          type: string
          description: Base asset symbol.
        baseAssetName:
          type: string
          description: Base asset name.
        baseAssetDecimals:
          type: integer
          format: int64
          description: Precision of the base asset.
        stepSizeE9:
          type: string
          description: Step size for the quantity (e9 format).
          example: 10000000
        tickSizeE9:
          type: string
          description: Price increment size (e9 format).
          example: 10000000
        minOrderQuantityE9:
          type: string
          description: Minimum order size (e9 format).
          example: 20000000
        maxLimitOrderQuantityE9:
          type: string
          description: Maximum limit order size (e9 format).
          example: 25000000000
        maxMarketOrderQuantityE9:
          type: string
          description: Maximum market order size (e9 format).
          example: 250000000000
        minOrderPriceE9:
          type: string
          description: Minimum order price (e9 format).
          example: 10000000
        maxOrderPriceE9:
          type: string
          description: Maximum order price (e9 format).
          example: 10000000000
        maintenanceMarginRatioE9:
          type: string
          description: Maintenance margin ratio (MMR, e9 format).
          example: 30000000
        initialMarginRatioE9:
          type: string
          description: Initial margin ratio (IMR), e9 format).
          example: 45000000
        insurancePoolRatioE9:
          type: string
          description: Insurance pool ratio (e9 format).
          example: 3000000
        defaultLeverageE9:
          type: string
          description: Default leverage (e9 format).
          example: 3000000000
        maxNotionalAtOpenE9:
          type: array
          description: Maximum notional value at current leverage. Index 0 is max notional value for leverage set to 1x, index 1 is for leverage 2x, etc...
          items:
            type: string
        minTradeQuantityE9:
          type: string
          description: Minimum trade quantity allowed (e9 format).
          example: 10000000
        maxTradeQuantityE9:
          type: string
          description: Max trade quantity allowed (e9 format).
          example: 100000000000
        minTradePriceE9:
          type: string
          description: Minimum trade price allowed (e9 format).
          example: 50000000000
        maxTradePriceE9:
          type: string
          description: Maximum trade price allowed (e9 format).
          example: 50000000000000
        maxFundingRateE9:
          type: string
          description: Maximum allowed funding rate (e9 format).
          example: 1000000
        defaultMakerFeeE9:
          type: string
          description: Default maker fee (e9 format).
          example: 150000
        defaultTakerFeeE9:
          type: string
          description: Default taker fee (e9 format).
          example: 550000
        insurancePoolAddress:
          type: string
          description: Insurance pool address.
        feePoolAddress:
          type: string
          description: Fee pool address.
        tradingStartTimeAtMillis:
          type: string
          description: The time when trading will start/have started on the market.
          example: 1724121094751
        mtbLongE9:
          type: string
          description: Maximum take bound for long positions (e9 format).
          example: 20000000
        mtbShortE9:
          type: string
          description: Maximum take bound for short positions (e9 format).
          example: 20000000
        delistingPriceE9:
          type: string
          description: Delisting price (e9 format).
          example: 200000000
        isolatedOnly:
          type: boolean
          description: Indicates whether the market only allows isolated margin.
      required:
        - symbol
        - marketAddress
        - status
        - baseAssetSymbol
        - baseAssetName
        - baseAssetDecimals
        - stepSizeE9
        - tickSizeE9
        - minOrderQuantityE9
        - maxLimitOrderQuantityE9
        - maxMarketOrderQuantityE9
        - minOrderPriceE9
        - maxOrderPriceE9
        - maintenanceMarginRatioE9
        - initialMarginRatioE9
        - insurancePoolRatioE9
        - defaultLeverageE9
        - maxNotionalAtOpenE9
        - minTradeQuantityE9
        - maxTradeQuantityE9
        - minTradePriceE9
        - maxTradePriceE9
        - maxFundingRateE9
        - defaultMakerFeeE9
        - defaultTakerFeeE9
        - insurancePoolAddress
        - feePoolAddress
        - tradingStartTimeAtMillis
        - mtbLongE9
        - mtbShortE9
        - delistingPriceE9
        - isolatedOnly

paths:
  /v1/exchange/info:
    get:
      tags:
        - Exchange
      operationId: getExchangeInfo
      summary: /exchange/info
      description: Returns the current exchange information including available margin assets, markets, and rules.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExchangeInfoResponse"
