# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.kora_campaign_bonus import KoraCampaignBonus
from typing import Optional, Set
from typing_extensions import Self

class KoraCampaignRewards(BaseModel):
    """
    KoraCampaignRewards
    """ # noqa: E501
    user_address: StrictStr = Field(description="User address for the rewards earned data", alias="userAddress")
    campaign_name: StrictStr = Field(description="Name of the campaign", alias="campaignName")
    epoch_number: StrictInt = Field(description="Epoch number for the rewards earned data", alias="epochNumber")
    interval_number: StrictInt = Field(description="Interval number for the rewards earned data", alias="intervalNumber")
    symbol: Optional[StrictStr] = Field(default=None, description="Market Symbol")
    status: StrictStr
    blue_rewards: Optional[StrictStr] = Field(default=None, description="Total blue token rewards", alias="blueRewards")
    sui_rewards: Optional[StrictStr] = Field(default=None, description="Total sui token rewards", alias="suiRewards")
    wal_rewards: Optional[StrictStr] = Field(default=None, description="Total wal rewards", alias="walRewards")
    cash_rewards: Optional[StrictStr] = Field(default=None, description="Total cash rewards", alias="cashRewards")
    cc_rewards: Optional[StrictStr] = Field(default=None, description="Total CC token rewards", alias="ccRewards")
    kora_points: Optional[StrictStr] = Field(default=None, description="Total Kora points earned", alias="koraPoints")
    user_fee_paid: Optional[StrictStr] = Field(default=None, description="Total user fee paid", alias="userFeePaid")
    interval_start_date: Optional[StrictInt] = Field(default=None, description="Time in milliseconds for interval start date", alias="intervalStartDate")
    interval_end_date: Optional[StrictInt] = Field(default=None, description="Time in milliseconds for interval end date", alias="intervalEndDate")
    is_disbursed: Optional[StrictBool] = Field(default=None, description="Indicates if rewards have been disbursed", alias="isDisbursed")
    txn_digest: Optional[StrictStr] = Field(default=None, description="Transaction digest of the disbursement", alias="txnDigest")
    claim_status: Optional[StrictStr] = Field(default=None, description="Status of the claim", alias="claimStatus")
    bonuses: Optional[List[KoraCampaignBonus]] = Field(default=None, description="List of bonuses attached to this reward entry")
    __properties: ClassVar[List[str]] = ["userAddress", "campaignName", "epochNumber", "intervalNumber", "symbol", "status", "blueRewards", "suiRewards", "walRewards", "cashRewards", "ccRewards", "koraPoints", "userFeePaid", "intervalStartDate", "intervalEndDate", "isDisbursed", "txnDigest", "claimStatus", "bonuses"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ACTIVE', 'NOT_STARTED', 'FINALIZED', 'COOLDOWN']):
            raise ValueError("must be one of enum values ('ACTIVE', 'NOT_STARTED', 'FINALIZED', 'COOLDOWN')")
        return value

    @field_validator('claim_status')
    def claim_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['CLAIMABLE', 'CLAIMED', 'NOT_YET_CLAIMABLE', 'CLAIM_ENDED']):
            raise ValueError("must be one of enum values ('CLAIMABLE', 'CLAIMED', 'NOT_YET_CLAIMABLE', 'CLAIM_ENDED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KoraCampaignRewards from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in bonuses (list)
        _items = []
        if self.bonuses:
            for _item_bonuses in self.bonuses:
                if _item_bonuses:
                    _items.append(_item_bonuses.to_dict())
            _dict['bonuses'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KoraCampaignRewards from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "userAddress": obj.get("userAddress"),
            "campaignName": obj.get("campaignName"),
            "epochNumber": obj.get("epochNumber"),
            "intervalNumber": obj.get("intervalNumber"),
            "symbol": obj.get("symbol"),
            "status": obj.get("status"),
            "blueRewards": obj.get("blueRewards"),
            "suiRewards": obj.get("suiRewards"),
            "walRewards": obj.get("walRewards"),
            "cashRewards": obj.get("cashRewards"),
            "ccRewards": obj.get("ccRewards"),
            "koraPoints": obj.get("koraPoints"),
            "userFeePaid": obj.get("userFeePaid"),
            "intervalStartDate": obj.get("intervalStartDate"),
            "intervalEndDate": obj.get("intervalEndDate"),
            "isDisbursed": obj.get("isDisbursed"),
            "txnDigest": obj.get("txnDigest"),
            "claimStatus": obj.get("claimStatus"),
            "bonuses": [KoraCampaignBonus.from_dict(_item) for _item in obj["bonuses"]] if obj.get("bonuses") is not None else None
        })
        return _obj


