# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class KoraEpochConfig(BaseModel):
    """
    KoraEpochConfig
    """ # noqa: E501
    campaign_name: StrictStr = Field(description="The name of the campaign", alias="campaignName")
    epoch_duration: StrictInt = Field(description="Duration of the epoch in hours", alias="epochDuration")
    sui_rewards_allocation: Optional[StrictStr] = Field(default=None, description="Allocation of Sui rewards for this epoch", alias="suiRewardsAllocation")
    blue_rewards_allocation: Optional[StrictStr] = Field(default=None, description="Allocation of Blue rewards for this epoch", alias="blueRewardsAllocation")
    wal_rewards_allocation: Optional[StrictStr] = Field(default=None, description="Allocation of Wal rewards for this epoch", alias="walRewardsAllocation")
    cc_rewards_allocation: Optional[StrictStr] = Field(default=None, description="Allocation of CC token rewards for this epoch", alias="ccRewardsAllocation")
    kora_points_rewards_allocation: Optional[StrictStr] = Field(default=None, description="Allocation of Kora points rewards for this epoch", alias="koraPointsRewardsAllocation")
    interval_number: StrictInt = Field(description="Interval number for the epoch", alias="intervalNumber")
    epoch_number: StrictInt = Field(description="Epoch number", alias="epochNumber")
    config: Optional[Dict[str, Any]] = Field(default=None, description="Additional campaign-specific configurations")
    __properties: ClassVar[List[str]] = ["campaignName", "epochDuration", "suiRewardsAllocation", "blueRewardsAllocation", "walRewardsAllocation", "ccRewardsAllocation", "koraPointsRewardsAllocation", "intervalNumber", "epochNumber", "config"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KoraEpochConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KoraEpochConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "campaignName": obj.get("campaignName"),
            "epochDuration": obj.get("epochDuration"),
            "suiRewardsAllocation": obj.get("suiRewardsAllocation"),
            "blueRewardsAllocation": obj.get("blueRewardsAllocation"),
            "walRewardsAllocation": obj.get("walRewardsAllocation"),
            "ccRewardsAllocation": obj.get("ccRewardsAllocation"),
            "koraPointsRewardsAllocation": obj.get("koraPointsRewardsAllocation"),
            "intervalNumber": obj.get("intervalNumber"),
            "epochNumber": obj.get("epochNumber"),
            "config": obj.get("config")
        })
        return _obj


