# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class KoraLeaderboardEntry(BaseModel):
    """
    KoraLeaderboardEntry
    """ # noqa: E501
    rank: StrictInt = Field(description="Overall ranking position based on sortBy parameter")
    user_address: StrictStr = Field(description="Wallet address of the user", alias="userAddress")
    total_volume_e6: StrictStr = Field(description="Total swap volume (USD equivalent)", alias="totalVolumeE6")
    total_fee_e6: Optional[StrictStr] = Field(default=None, description="Total fees paid", alias="totalFeeE6")
    total_transactions: StrictInt = Field(description="Total number of qualifying swap transactions", alias="totalTransactions")
    cc_rewards: StrictStr = Field(description="CC token rewards earned", alias="ccRewards")
    kora_points: StrictStr = Field(description="Kora points earned", alias="koraPoints")
    total_bonus_points: Optional[StrictStr] = Field(default=None, description="Total bonus points earned", alias="totalBonusPoints")
    total_bonus_cc: Optional[StrictStr] = Field(default=None, description="Total bonus CC tokens earned", alias="totalBonusCC")
    volume_rank: Optional[StrictInt] = Field(default=None, description="Ranking based purely on trading volume", alias="volumeRank")
    transaction_rank: Optional[StrictInt] = Field(default=None, description="Ranking based purely on transaction count", alias="transactionRank")
    total_earnings_rank: Optional[StrictInt] = Field(default=None, description="Ranking based on combined CC + Kora points value", alias="totalEarningsRank")
    last_activity_date: Optional[StrictInt] = Field(default=None, description="Timestamp of user's most recent swap (milliseconds)", alias="lastActivityDate")
    __properties: ClassVar[List[str]] = ["rank", "userAddress", "totalVolumeE6", "totalFeeE6", "totalTransactions", "ccRewards", "koraPoints", "totalBonusPoints", "totalBonusCC", "volumeRank", "transactionRank", "totalEarningsRank", "lastActivityDate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KoraLeaderboardEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KoraLeaderboardEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rank": obj.get("rank"),
            "userAddress": obj.get("userAddress"),
            "totalVolumeE6": obj.get("totalVolumeE6"),
            "totalFeeE6": obj.get("totalFeeE6"),
            "totalTransactions": obj.get("totalTransactions"),
            "ccRewards": obj.get("ccRewards"),
            "koraPoints": obj.get("koraPoints"),
            "totalBonusPoints": obj.get("totalBonusPoints"),
            "totalBonusCC": obj.get("totalBonusCC"),
            "volumeRank": obj.get("volumeRank"),
            "transactionRank": obj.get("transactionRank"),
            "totalEarningsRank": obj.get("totalEarningsRank"),
            "lastActivityDate": obj.get("lastActivityDate")
        })
        return _obj


