# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class StatsEntry(BaseModel):
    """
    StatsEntry
    """ # noqa: E501
    start_time_at_millis: StrictInt = Field(description="Timestamp in milliseconds when the statistics period starts.", alias="startTimeAtMillis")
    legacy_tvl_e9: StrictStr = Field(description="Total value locked in the legacy exchange in e9 format.", alias="legacyTvlE9")
    tvl_e9: StrictStr = Field(description="Total value locked in the exchange in e9 format.", alias="tvlE9")
    total_legacy_quote_asset_volume_e9: StrictStr = Field(description="Total quote asset volume in the legacy exchange in e9 format.", alias="totalLegacyQuoteAssetVolumeE9")
    total_quote_asset_volume_e9: StrictStr = Field(description="Total quote asset volume in the exchange in e9 format.", alias="totalQuoteAssetVolumeE9")
    end_time_at_millis: StrictInt = Field(description="Timestamp in milliseconds when the statistics period ends.", alias="endTimeAtMillis")
    __properties: ClassVar[List[str]] = ["startTimeAtMillis", "legacyTvlE9", "tvlE9", "totalLegacyQuoteAssetVolumeE9", "totalQuoteAssetVolumeE9", "endTimeAtMillis"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatsEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatsEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "startTimeAtMillis": obj.get("startTimeAtMillis"),
            "legacyTvlE9": obj.get("legacyTvlE9"),
            "tvlE9": obj.get("tvlE9"),
            "totalLegacyQuoteAssetVolumeE9": obj.get("totalLegacyQuoteAssetVolumeE9"),
            "totalQuoteAssetVolumeE9": obj.get("totalQuoteAssetVolumeE9"),
            "endTimeAtMillis": obj.get("endTimeAtMillis")
        })
        return _obj


