# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.claim_signature_item import ClaimSignatureItem
from typing import Optional, Set
from typing_extensions import Self

class UserCampaignRewards(BaseModel):
    """
    UserCampaignRewards
    """ # noqa: E501
    user_address: StrictStr = Field(description="User address for the rewards earned data.", alias="userAddress")
    campaign_name: StrictStr = Field(description="Name of the campaign.", alias="campaignName")
    epoch_number: StrictInt = Field(description="Epoch number for the rewards earned data.", alias="epochNumber")
    interval_number: StrictInt = Field(description="Interval number for the rewards earned data.", alias="intervalNumber")
    symbol: StrictStr = Field(description="Market Symbol.")
    status: StrictStr
    blue_rewards_e9: StrictStr = Field(description="Total blue-perp token rewards earned in the epoch (e9 format).", alias="blueRewardsE9")
    sui_rewards_e9: StrictStr = Field(description="Total sui-perp token rewards earned in the epoch (e9 format).", alias="suiRewardsE9")
    wal_rewards_e9: StrictStr = Field(description="Total wal-perp rewards earned in the epoch (e9 format).", alias="walRewardsE9")
    cash_rewards_e9: StrictStr = Field(description="Total cash rewards earned in the epoch (e9 format).", alias="cashRewardsE9")
    user_fee_paid_e9: StrictStr = Field(description="Total user fee paid in the epoch (e9 format).", alias="userFeePaidE9")
    interval_start_date: StrictInt = Field(description="Time in milliseconds for interval start date.", alias="intervalStartDate")
    interval_end_date: StrictInt = Field(description="Time in milliseconds for interval end date.", alias="intervalEndDate")
    is_disbursed: StrictBool = Field(description="Indicates if the rewards have been disbursed.", alias="isDisbursed")
    txn_digest: StrictStr = Field(description="Transaction digest of the disbursement.", alias="txnDigest")
    claim_signature: Optional[List[ClaimSignatureItem]] = Field(default=None, description="Array of claim signatures for different reward types.", alias="claimSignature")
    claim_status: Optional[StrictStr] = Field(default=None, description="Status of the claim.", alias="claimStatus")
    __properties: ClassVar[List[str]] = ["userAddress", "campaignName", "epochNumber", "intervalNumber", "symbol", "status", "blueRewardsE9", "suiRewardsE9", "walRewardsE9", "cashRewardsE9", "userFeePaidE9", "intervalStartDate", "intervalEndDate", "isDisbursed", "txnDigest", "claimSignature", "claimStatus"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ACTIVE', 'NOT_STARTED', 'FINALIZED', 'COOLDOWN']):
            raise ValueError("must be one of enum values ('ACTIVE', 'NOT_STARTED', 'FINALIZED', 'COOLDOWN')")
        return value

    @field_validator('claim_status')
    def claim_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['CLAIMABLE', 'CLAIMED', 'NOT_YET_CLAIMABLE', 'CLAIM_ENDED']):
            raise ValueError("must be one of enum values ('CLAIMABLE', 'CLAIMED', 'NOT_YET_CLAIMABLE', 'CLAIM_ENDED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserCampaignRewards from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in claim_signature (list)
        _items = []
        if self.claim_signature:
            for _item_claim_signature in self.claim_signature:
                if _item_claim_signature:
                    _items.append(_item_claim_signature.to_dict())
            _dict['claimSignature'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserCampaignRewards from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "userAddress": obj.get("userAddress"),
            "campaignName": obj.get("campaignName"),
            "epochNumber": obj.get("epochNumber"),
            "intervalNumber": obj.get("intervalNumber"),
            "symbol": obj.get("symbol"),
            "status": obj.get("status"),
            "blueRewardsE9": obj.get("blueRewardsE9"),
            "suiRewardsE9": obj.get("suiRewardsE9"),
            "walRewardsE9": obj.get("walRewardsE9"),
            "cashRewardsE9": obj.get("cashRewardsE9"),
            "userFeePaidE9": obj.get("userFeePaidE9"),
            "intervalStartDate": obj.get("intervalStartDate"),
            "intervalEndDate": obj.get("intervalEndDate"),
            "isDisbursed": obj.get("isDisbursed"),
            "txnDigest": obj.get("txnDigest"),
            "claimSignature": [ClaimSignatureItem.from_dict(_item) for _item in obj["claimSignature"]] if obj.get("claimSignature") is not None else None,
            "claimStatus": obj.get("claimStatus")
        })
        return _obj


