# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.iss_base64_details import IssBase64Details
from openapi_client.models.proof_points import ProofPoints
from typing import Optional, Set
from typing_extensions import Self

class ZKLoginZKPResponse(BaseModel):
    """
    ZKLoginZKPResponse
    """ # noqa: E501
    proof_points: Optional[ProofPoints] = Field(default=None, alias="proofPoints")
    iss_base64_details: Optional[IssBase64Details] = Field(default=None, alias="issBase64Details")
    header_base64: Optional[StrictStr] = Field(default=None, description="Base64 encoded header information.", alias="headerBase64")
    address_seed: StrictStr = Field(description="The address seed used in the proof.", alias="addressSeed")
    __properties: ClassVar[List[str]] = ["proofPoints", "issBase64Details", "headerBase64", "addressSeed"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ZKLoginZKPResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of proof_points
        if self.proof_points:
            _dict['proofPoints'] = self.proof_points.to_dict()
        # override the default output from pydantic by calling `to_dict()` of iss_base64_details
        if self.iss_base64_details:
            _dict['issBase64Details'] = self.iss_base64_details.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ZKLoginZKPResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "proofPoints": ProofPoints.from_dict(obj["proofPoints"]) if obj.get("proofPoints") is not None else None,
            "issBase64Details": IssBase64Details.from_dict(obj["issBase64Details"]) if obj.get("issBase64Details") is not None else None,
            "headerBase64": obj.get("headerBase64"),
            "addressSeed": obj.get("addressSeed")
        })
        return _obj


