# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sig_payload import SigPayload

class TestSigPayload(unittest.TestCase):
    """SigPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SigPayload:
        """Test SigPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SigPayload`
        """
        model = SigPayload()
        if include_optional:
            return SigPayload(
                target = '',
                receiver = '',
                amount = '',
                expiry = '',
                nonce = '',
                type = 0
            )
        else:
            return SigPayload(
                target = '',
                receiver = '',
                amount = '',
                expiry = '',
                nonce = '',
                type = 0,
        )
        """

    def testSigPayload(self):
        """Test SigPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
