# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.kora_campaign_rewards import KoraCampaignRewards

class TestKoraCampaignRewards(unittest.TestCase):
    """KoraCampaignRewards unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KoraCampaignRewards:
        """Test KoraCampaignRewards
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KoraCampaignRewards`
        """
        model = KoraCampaignRewards()
        if include_optional:
            return KoraCampaignRewards(
                user_address = '0x1234567890abcdef',
                campaign_name = 'KORA_SWAPS',
                epoch_number = 7,
                interval_number = 7,
                symbol = 'KORA-SWAPS',
                status = 'ACTIVE',
                blue_rewards = '100.5',
                sui_rewards = '200.25',
                wal_rewards = '50.75',
                cash_rewards = '0',
                cc_rewards = '1500.75',
                kora_points = '2500.5',
                user_fee_paid = '15.25',
                interval_start_date = 1724121094751,
                interval_end_date = 1724725894751,
                is_disbursed = True,
                txn_digest = '8Fs9Q4ljB0cc0NhcqSVZRgTxe9KwZeRqjGYYYe4jXgXL',
                claim_status = 'CLAIMED',
                bonuses = [
                    openapi_client.models.kora_campaign_bonus.KoraCampaignBonus(
                        bonus_type = 'VOLUME_BONUS', 
                        bonus_cc_reward = '500.5', 
                        bonus_points = '1000.75', 
                        bonus_criteria = 'volume_threshold_100k', )
                    ]
            )
        else:
            return KoraCampaignRewards(
                user_address = '0x1234567890abcdef',
                campaign_name = 'KORA_SWAPS',
                epoch_number = 7,
                interval_number = 7,
                status = 'ACTIVE',
        )
        """

    def testKoraCampaignRewards(self):
        """Test KoraCampaignRewards"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
