# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.stats_all_time_response import StatsAllTimeResponse

class TestStatsAllTimeResponse(unittest.TestCase):
    """StatsAllTimeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsAllTimeResponse:
        """Test StatsAllTimeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsAllTimeResponse`
        """
        model = StatsAllTimeResponse()
        if include_optional:
            return StatsAllTimeResponse(
                start_time_at_millis = 1753920000000,
                legacy_tvl_e9 = '1000000000000000000',
                tvl_e9 = '1000000000000000000',
                total_legacy_quote_asset_volume_e9 = '1000000000000000000',
                total_quote_asset_volume_e9 = '1000000000000000000',
                end_time_at_millis = 1754006399999
            )
        else:
            return StatsAllTimeResponse(
                start_time_at_millis = 1753920000000,
                legacy_tvl_e9 = '1000000000000000000',
                tvl_e9 = '1000000000000000000',
                total_legacy_quote_asset_volume_e9 = '1000000000000000000',
                total_quote_asset_volume_e9 = '1000000000000000000',
                end_time_at_millis = 1754006399999,
        )
        """

    def testStatsAllTimeResponse(self):
        """Test StatsAllTimeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
