# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.kora_user_bonus_response import KoraUserBonusResponse

class TestKoraUserBonusResponse(unittest.TestCase):
    """KoraUserBonusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KoraUserBonusResponse:
        """Test KoraUserBonusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KoraUserBonusResponse`
        """
        model = KoraUserBonusResponse()
        if include_optional:
            return KoraUserBonusResponse(
                user_address = '0x1234567890abcdef',
                epoch_number = 7,
                bonus_points = '1000.75',
                bonus_cc_rewards = '500.5',
                criteria = 'volume_threshold_100k'
            )
        else:
            return KoraUserBonusResponse(
                user_address = '0x1234567890abcdef',
                epoch_number = 7,
                bonus_points = '1000.75',
                bonus_cc_rewards = '500.5',
        )
        """

    def testKoraUserBonusResponse(self):
        """Test KoraUserBonusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
