# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.mark_as_claimed_request import MarkAsClaimedRequest

class TestMarkAsClaimedRequest(unittest.TestCase):
    """MarkAsClaimedRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarkAsClaimedRequest:
        """Test MarkAsClaimedRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarkAsClaimedRequest`
        """
        model = MarkAsClaimedRequest()
        if include_optional:
            return MarkAsClaimedRequest(
                interval_number = 1,
                campaign_name = 'TRADE_AND_EARN',
                txn_digest = '0x1234567890abcdef',
                reward_types = [[BLUE, SUI]]
            )
        else:
            return MarkAsClaimedRequest(
                interval_number = 1,
                campaign_name = 'TRADE_AND_EARN',
                txn_digest = '0x1234567890abcdef',
                reward_types = [[BLUE, SUI]],
        )
        """

    def testMarkAsClaimedRequest(self):
        """Test MarkAsClaimedRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
