# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.account_update import AccountUpdate

class TestAccountUpdate(unittest.TestCase):
    """AccountUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountUpdate:
        """Test AccountUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountUpdate`
        """
        model = AccountUpdate()
        if include_optional:
            return AccountUpdate(
                trading_fees = openapi_client.models.trading_fees.TradingFees(
                    maker_fee_e9 = '1000000', 
                    taker_fee_e9 = '1000000', 
                    is_applied = True, ),
                can_trade = True,
                can_deposit = True,
                can_withdraw = True,
                total_effective_balance_e9 = '',
                total_initial_margin_required_e9 = '',
                total_open_order_initial_margin_required_e9 = '',
                initial_margin_available_e9 = '',
                total_maintenance_margin_required_e9 = '',
                maintenance_margin_available_e9 = '',
                account_maintenance_margin_ratio_e9 = '',
                account_leverage_e9 = '',
                total_unrealized_pnl_e9 = '',
                total_cross_unrealized_pnl_e9 = '',
                updated_at_millis = 56,
                assets = [
                    openapi_client.models.asset.Asset(
                        symbol = '', 
                        quantity_e9 = '', 
                        effective_balance_e9 = '', 
                        max_withdraw_quantity_e9 = '', 
                        updated_at_millis = 56, )
                    ]
            )
        else:
            return AccountUpdate(
                can_trade = True,
                can_deposit = True,
                can_withdraw = True,
                total_effective_balance_e9 = '',
                total_initial_margin_required_e9 = '',
                total_open_order_initial_margin_required_e9 = '',
                initial_margin_available_e9 = '',
                total_maintenance_margin_required_e9 = '',
                maintenance_margin_available_e9 = '',
                account_maintenance_margin_ratio_e9 = '',
                account_leverage_e9 = '',
                total_unrealized_pnl_e9 = '',
                total_cross_unrealized_pnl_e9 = '',
                updated_at_millis = 56,
                assets = [
                    openapi_client.models.asset.Asset(
                        symbol = '', 
                        quantity_e9 = '', 
                        effective_balance_e9 = '', 
                        max_withdraw_quantity_e9 = '', 
                        updated_at_millis = 56, )
                    ],
        )
        """

    def testAccountUpdate(self):
        """Test AccountUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
