# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.onboard_affiliate_request_social_user_names import OnboardAffiliateRequestSocialUserNames

class TestOnboardAffiliateRequestSocialUserNames(unittest.TestCase):
    """OnboardAffiliateRequestSocialUserNames unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OnboardAffiliateRequestSocialUserNames:
        """Test OnboardAffiliateRequestSocialUserNames
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OnboardAffiliateRequestSocialUserNames`
        """
        model = OnboardAffiliateRequestSocialUserNames()
        if include_optional:
            return OnboardAffiliateRequestSocialUserNames(
                twitter = '@johndoe',
                instagram = '@johndoe',
                youtube = 'JohnDoeChannel',
                tiktok = '@johndoe'
            )
        else:
            return OnboardAffiliateRequestSocialUserNames(
        )
        """

    def testOnboardAffiliateRequestSocialUserNames(self):
        """Test OnboardAffiliateRequestSocialUserNames"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
