# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.kora_leaderboard_response import KoraLeaderboardResponse

class TestKoraLeaderboardResponse(unittest.TestCase):
    """KoraLeaderboardResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KoraLeaderboardResponse:
        """Test KoraLeaderboardResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KoraLeaderboardResponse`
        """
        model = KoraLeaderboardResponse()
        if include_optional:
            return KoraLeaderboardResponse(
                data = [
                    openapi_client.models.kora_leaderboard_entry.KoraLeaderboardEntry(
                        rank = 1, 
                        user_address = '0x1234567890abcdef', 
                        total_volume_e6 = '50000.123456', 
                        total_fee_e6 = '150.75', 
                        total_transactions = 1250, 
                        cc_rewards = '1500.75', 
                        kora_points = '2500.5', 
                        total_bonus_points = '500.25', 
                        total_bonus_cc = '200.5', 
                        volume_rank = 1, 
                        transaction_rank = 3, 
                        total_earnings_rank = 1, 
                        last_activity_date = 1724725894751, )
                    ],
                total = 2847,
                limit = 500,
                page = 1
            )
        else:
            return KoraLeaderboardResponse(
                data = [
                    openapi_client.models.kora_leaderboard_entry.KoraLeaderboardEntry(
                        rank = 1, 
                        user_address = '0x1234567890abcdef', 
                        total_volume_e6 = '50000.123456', 
                        total_fee_e6 = '150.75', 
                        total_transactions = 1250, 
                        cc_rewards = '1500.75', 
                        kora_points = '2500.5', 
                        total_bonus_points = '500.25', 
                        total_bonus_cc = '200.5', 
                        volume_rank = 1, 
                        transaction_rank = 3, 
                        total_earnings_rank = 1, 
                        last_activity_date = 1724725894751, )
                    ],
                total = 2847,
                limit = 500,
                page = 1,
        )
        """

    def testKoraLeaderboardResponse(self):
        """Test KoraLeaderboardResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
