# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.open_id_configuration_response import OpenIDConfigurationResponse

class TestOpenIDConfigurationResponse(unittest.TestCase):
    """OpenIDConfigurationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenIDConfigurationResponse:
        """Test OpenIDConfigurationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenIDConfigurationResponse`
        """
        model = OpenIDConfigurationResponse()
        if include_optional:
            return OpenIDConfigurationResponse(
                issuer = '',
                authorization_endpoint = '',
                jwks_uri = '',
                token_endpoint = '',
                response_types_supported = [
                    ''
                    ],
                id_token_signing_alg_values_supported = [
                    ''
                    ],
                subject_types_supported = [
                    ''
                    ],
                scopes_supported = [
                    ''
                    ]
            )
        else:
            return OpenIDConfigurationResponse(
                issuer = '',
                authorization_endpoint = '',
                jwks_uri = '',
                token_endpoint = '',
                response_types_supported = [
                    ''
                    ],
                id_token_signing_alg_values_supported = [
                    ''
                    ],
                subject_types_supported = [
                    ''
                    ],
                scopes_supported = [
                    ''
                    ],
        )
        """

    def testOpenIDConfigurationResponse(self):
        """Test OpenIDConfigurationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
