# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_rewards_metadata_interval_get_interval_parameter import V1RewardsMetadataIntervalGetIntervalParameter

class TestV1RewardsMetadataIntervalGetIntervalParameter(unittest.TestCase):
    """V1RewardsMetadataIntervalGetIntervalParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1RewardsMetadataIntervalGetIntervalParameter:
        """Test V1RewardsMetadataIntervalGetIntervalParameter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1RewardsMetadataIntervalGetIntervalParameter`
        """
        model = V1RewardsMetadataIntervalGetIntervalParameter()
        if include_optional:
            return V1RewardsMetadataIntervalGetIntervalParameter(
            )
        else:
            return V1RewardsMetadataIntervalGetIntervalParameter(
        )
        """

    def testV1RewardsMetadataIntervalGetIntervalParameter(self):
        """Test V1RewardsMetadataIntervalGetIntervalParameter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
