# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.oracle_price_update import OraclePriceUpdate

class TestOraclePriceUpdate(unittest.TestCase):
    """OraclePriceUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OraclePriceUpdate:
        """Test OraclePriceUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OraclePriceUpdate`
        """
        model = OraclePriceUpdate()
        if include_optional:
            return OraclePriceUpdate(
                symbol = '',
                price_e9 = '',
                source = 'Oracle',
                updated_at_millis = 56
            )
        else:
            return OraclePriceUpdate(
                symbol = '',
                price_e9 = '',
                source = 'Oracle',
                updated_at_millis = 56,
        )
        """

    def testOraclePriceUpdate(self):
        """Test OraclePriceUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
