# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_account_value_history_params_interval import GetAccountValueHistoryParamsInterval

class TestGetAccountValueHistoryParamsInterval(unittest.TestCase):
    """GetAccountValueHistoryParamsInterval unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAccountValueHistoryParamsInterval(self):
        """Test GetAccountValueHistoryParamsInterval"""
        # inst = GetAccountValueHistoryParamsInterval()

if __name__ == '__main__':
    unittest.main()
