# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.leaderboard_entry1 import LeaderboardEntry1

class TestLeaderboardEntry1(unittest.TestCase):
    """LeaderboardEntry1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LeaderboardEntry1:
        """Test LeaderboardEntry1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LeaderboardEntry1`
        """
        model = LeaderboardEntry1()
        if include_optional:
            return LeaderboardEntry1(
                rank = 56,
                user_address = '',
                total_points = '',
                current_tier = 'NONE'
            )
        else:
            return LeaderboardEntry1(
                rank = 56,
                user_address = '',
                total_points = '',
                current_tier = 'NONE',
        )
        """

    def testLeaderboardEntry1(self):
        """Test LeaderboardEntry1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
