# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.kora_leaderboard_entry import KoraLeaderboardEntry

class TestKoraLeaderboardEntry(unittest.TestCase):
    """KoraLeaderboardEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KoraLeaderboardEntry:
        """Test KoraLeaderboardEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KoraLeaderboardEntry`
        """
        model = KoraLeaderboardEntry()
        if include_optional:
            return KoraLeaderboardEntry(
                rank = 1,
                user_address = '0x1234567890abcdef',
                total_volume_e6 = '50000.123456',
                total_fee_e6 = '150.75',
                total_transactions = 1250,
                cc_rewards = '1500.75',
                kora_points = '2500.5',
                total_bonus_points = '500.25',
                total_bonus_cc = '200.5',
                volume_rank = 1,
                transaction_rank = 3,
                total_earnings_rank = 1,
                last_activity_date = 1724725894751
            )
        else:
            return KoraLeaderboardEntry(
                rank = 1,
                user_address = '0x1234567890abcdef',
                total_volume_e6 = '50000.123456',
                total_transactions = 1250,
                cc_rewards = '1500.75',
                kora_points = '2500.5',
        )
        """

    def testKoraLeaderboardEntry(self):
        """Test KoraLeaderboardEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
