# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.failed_command_type import FailedCommandType

class TestFailedCommandType(unittest.TestCase):
    """FailedCommandType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFailedCommandType(self):
        """Test FailedCommandType"""
        # inst = FailedCommandType()

if __name__ == '__main__':
    unittest.main()
