/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccountPositionLeverageUpdateRequestSignedFields
 */
export interface AccountPositionLeverageUpdateRequestSignedFields {
    /**
     * The Account Address from which to update leverage
     * @type {string}
     * @memberof AccountPositionLeverageUpdateRequestSignedFields
     */
    'accountAddress': string;
    /**
     * Symbol of the perpetual of the positions for which to update the leverage
     * @type {string}
     * @memberof AccountPositionLeverageUpdateRequestSignedFields
     */
    'symbol': string;
    /**
     * The leverage to set for the account positions (Must be a number in base e9)
     * @type {string}
     * @memberof AccountPositionLeverageUpdateRequestSignedFields
     */
    'leverageE9': string;
    /**
     * The random generated SALT. Should always be a number
     * @type {string}
     * @memberof AccountPositionLeverageUpdateRequestSignedFields
     */
    'salt': string;
    /**
     * the ID of the internal datastore for the target network
     * @type {string}
     * @memberof AccountPositionLeverageUpdateRequestSignedFields
     */
    'idsId': string;
    /**
     * The timestamp in millis at which the request was signed
     * @type {number}
     * @memberof AccountPositionLeverageUpdateRequestSignedFields
     */
    'signedAtMillis': number;
}

