/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Trade } from './trade';

/**
 * Details about a trade in the account.
 * @export
 * @interface AccountTradeUpdate
 */
export interface AccountTradeUpdate {
    /**
     * 
     * @type {Trade}
     * @memberof AccountTradeUpdate
     */
    'trade': Trade;
}

