/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PositionSide } from './position-side';

/**
 * 
 * @export
 * @interface AccountFundingRateHistoryData
 */
export interface AccountFundingRateHistoryData {
    /**
     * Payment amount in e9 format.
     * @type {string}
     * @memberof AccountFundingRateHistoryData
     */
    'paymentAmountE9': string;
    /**
     * 
     * @type {PositionSide}
     * @memberof AccountFundingRateHistoryData
     */
    'positionSide': PositionSide;
    /**
     * Funding rate value (e9 format).
     * @type {string}
     * @memberof AccountFundingRateHistoryData
     */
    'rateE9': string;
    /**
     * Market address.
     * @type {string}
     * @memberof AccountFundingRateHistoryData
     */
    'symbol': string;
    /**
     * Execution timestamp in milliseconds since Unix epoch.
     * @type {number}
     * @memberof AccountFundingRateHistoryData
     */
    'executedAtMillis': number;
    /**
     * Computed timestamp in milliseconds since Unix epoch.
     * @type {number}
     * @memberof AccountFundingRateHistoryData
     */
    'computedAtMillis': number;
}



