/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ActiveOrderUpdate } from './active-order-update';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderCancelReason } from './order-cancel-reason';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderCancellationFailureReason } from './order-cancellation-failure-reason';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderCancellationUpdate } from './order-cancellation-update';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderStatus } from './order-status';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderTimeInForce } from './order-time-in-force';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderType } from './order-type';
// May contain unused imports in some cases
// @ts-ignore
import type { SelfTradePreventionType } from './self-trade-prevention-type';
// May contain unused imports in some cases
// @ts-ignore
import type { TradeSide } from './trade-side';

/**
 * @type AccountOrderUpdate
 * A message containing order update information.
 * @export
 */
export type AccountOrderUpdate = ActiveOrderUpdate | OrderCancellationUpdate;


