/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AffiliateIntervalOverview
 */
export interface AffiliateIntervalOverview {
    /**
     * The user\'s wallet address
     * @type {string}
     * @memberof AffiliateIntervalOverview
     */
    'userAddress': string;
    /**
     * Name of the affiliate
     * @type {string}
     * @memberof AffiliateIntervalOverview
     */
    'name'?: string;
    /**
     * The interval number for the affiliate\'s earnings data
     * @type {number}
     * @memberof AffiliateIntervalOverview
     */
    'intervalNumber': number;
    /**
     * Start date of the interval in seconds
     * @type {number}
     * @memberof AffiliateIntervalOverview
     */
    'intervalStartDate': number;
    /**
     * End date of the interval in seconds
     * @type {number}
     * @memberof AffiliateIntervalOverview
     */
    'intervalEndDate': number;
    /**
     * Status of the interval
     * @type {string}
     * @memberof AffiliateIntervalOverview
     */
    'status': AffiliateIntervalOverviewStatusEnum;
    /**
     * Date when the user was referred
     * @type {string}
     * @memberof AffiliateIntervalOverview
     */
    'referredSince': string;
    /**
     * Referee earnings from perps trading (e9 format)
     * @type {string}
     * @memberof AffiliateIntervalOverview
     */
    'perpsRefereeEarningsE9': string;
    /**
     * Referee earnings from spot LP (e9 format)
     * @type {string}
     * @memberof AffiliateIntervalOverview
     */
    'spotLPRefereeEarningsE9': string;
    /**
     * Referee earnings from lending (e9 format)
     * @type {string}
     * @memberof AffiliateIntervalOverview
     */
    'lendingRefereeEarningsE9': string;
    /**
     * Referral earnings from perps trading (e9 format)
     * @type {string}
     * @memberof AffiliateIntervalOverview
     */
    'perpsReferralEarningsE9': string;
    /**
     * Referral earnings from spot LP (e9 format)
     * @type {string}
     * @memberof AffiliateIntervalOverview
     */
    'spotLPReferralEarningsE9': string;
    /**
     * Referral earnings from lending (e9 format)
     * @type {string}
     * @memberof AffiliateIntervalOverview
     */
    'lendingReferralEarningsE9': string;
    /**
     * Total earnings from perps trading (e9 format)
     * @type {string}
     * @memberof AffiliateIntervalOverview
     */
    'perpsTotalEarningsE9': string;
    /**
     * Total earnings from spot LP (e9 format)
     * @type {string}
     * @memberof AffiliateIntervalOverview
     */
    'spotLPTotalEarningsE9': string;
    /**
     * Total earnings from lending (e9 format)
     * @type {string}
     * @memberof AffiliateIntervalOverview
     */
    'lendingTotalEarningsE9': string;
    /**
     * Total earnings from referrals (e9 format)
     * @type {string}
     * @memberof AffiliateIntervalOverview
     */
    'totalReferralEarningsE9': string;
    /**
     * Total earnings from referee activities (e9 format)
     * @type {string}
     * @memberof AffiliateIntervalOverview
     */
    'totalRefereeEarningsE9': string;
    /**
     * Total earnings combining referrals and referee activities (e9 format)
     * @type {string}
     * @memberof AffiliateIntervalOverview
     */
    'totalEarningsE9': string;
}

export const AffiliateIntervalOverviewStatusEnum = {
    Active: 'ACTIVE',
    NotStarted: 'NOT_STARTED',
    Finalized: 'FINALIZED',
    Cooldown: 'COOLDOWN'
} as const;

export type AffiliateIntervalOverviewStatusEnum = typeof AffiliateIntervalOverviewStatusEnum[keyof typeof AffiliateIntervalOverviewStatusEnum];


