/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AffiliateLeaderDashboard
 */
export interface AffiliateLeaderDashboard {
    /**
     * The user\'s wallet address
     * @type {string}
     * @memberof AffiliateLeaderDashboard
     */
    'userAddress': string;
    /**
     * Name of the affiliate
     * @type {string}
     * @memberof AffiliateLeaderDashboard
     */
    'name'?: string;
    /**
     * The parent affiliate\'s wallet address
     * @type {string}
     * @memberof AffiliateLeaderDashboard
     */
    'parentAddress': string;
    /**
     * Name of the parent affiliate
     * @type {string}
     * @memberof AffiliateLeaderDashboard
     */
    'parentName'?: string;
    /**
     * Ranking in perps trading category
     * @type {number}
     * @memberof AffiliateLeaderDashboard
     */
    'perpsRank': number;
    /**
     * Ranking in spot trading category
     * @type {number}
     * @memberof AffiliateLeaderDashboard
     */
    'spotRank': number;
    /**
     * Ranking in lending category
     * @type {number}
     * @memberof AffiliateLeaderDashboard
     */
    'lendingRank': number;
    /**
     * Total earnings from perps trading (e9 format)
     * @type {string}
     * @memberof AffiliateLeaderDashboard
     */
    'perpsTotalEarningsE9': string;
    /**
     * Total earnings from spot trading (e9 format)
     * @type {string}
     * @memberof AffiliateLeaderDashboard
     */
    'spotTotalEarningsE9': string;
    /**
     * Total earnings from lending (e9 format)
     * @type {string}
     * @memberof AffiliateLeaderDashboard
     */
    'lendingTotalEarningsE9': string;
}

