/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AssetConfig
 */
export interface AssetConfig {
    /**
     * The bank address of the asset.
     * @type {string}
     * @memberof AssetConfig
     */
    'assetType': string;
    /**
     * Asset symbol.
     * @type {string}
     * @memberof AssetConfig
     */
    'symbol': string;
    /**
     * Default precision for rendering this asset.
     * @type {number}
     * @memberof AssetConfig
     */
    'decimals': number;
    /**
     * Weight applied to asset to use as margin in Multi-Assets mode.
     * @type {string}
     * @memberof AssetConfig
     */
    'weight': string;
    /**
     * Indicates if the asset can be used as margin in Multi-Assets mode.
     * @type {boolean}
     * @memberof AssetConfig
     */
    'marginAvailable': boolean;
}

