/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthorizedWallet
 */
export interface AuthorizedWallet {
    /**
     * The address of the authorized wallet.
     * @type {string}
     * @memberof AuthorizedWallet
     */
    'address': string;
    /**
     * The alias of the authorized wallet.
     * @type {string}
     * @memberof AuthorizedWallet
     */
    'alias'?: string;
    /**
     * The timestamp in milliseconds when the wallet was authorized.
     * @type {number}
     * @memberof AuthorizedWallet
     */
    'authorizedAtMillis': number;
}

