/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateOrderRequestSignedFields } from './create-order-request-signed-fields';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderTimeInForce } from './order-time-in-force';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderType } from './order-type';
// May contain unused imports in some cases
// @ts-ignore
import type { SelfTradePreventionType } from './self-trade-prevention-type';

/**
 * 
 * @export
 * @interface CreateOrderRequest
 */
export interface CreateOrderRequest {
    /**
     * 
     * @type {CreateOrderRequestSignedFields}
     * @memberof CreateOrderRequest
     */
    'signedFields': CreateOrderRequestSignedFields;
    /**
     * The signature of the request, encoded from the signedFields
     * @type {string}
     * @memberof CreateOrderRequest
     */
    'signature': string;
    /**
     * The client-defined unique identifier of this order used for lookup. This should always be unique; however, the server will not gurantee this or impose any checks.
     * @type {string}
     * @memberof CreateOrderRequest
     */
    'clientOrderId'?: string;
    /**
     * 
     * @type {OrderType}
     * @memberof CreateOrderRequest
     */
    'type': OrderType;
    /**
     * Is this order to only reduce a position? Default false
     * @type {boolean}
     * @memberof CreateOrderRequest
     */
    'reduceOnly': boolean;
    /**
     * If set to TRUE, the order can only be a maker order
     * @type {boolean}
     * @memberof CreateOrderRequest
     */
    'postOnly'?: boolean;
    /**
     * Omit or set to null for market orders; otherwise, choose a valid time-in-force value. GTT: Good Til Time  IOC: Immediate Or Cancel  FOK: Fill Or Kill 
     * @type {OrderTimeInForce}
     * @memberof CreateOrderRequest
     */
    'timeInForce'?: OrderTimeInForce;
    /**
     * Trigger price in base e9 for stop orders. This should always be a number
     * @type {string}
     * @memberof CreateOrderRequest
     */
    'triggerPriceE9'?: string;
    /**
     * 
     * @type {SelfTradePreventionType}
     * @memberof CreateOrderRequest
     */
    'selfTradePreventionType'?: SelfTradePreventionType;
}



