/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Map of various fee-related configurations
 * @export
 * @interface FeeConfigs
 */
export interface FeeConfigs {
    /**
     * Earnings from referral perps fees
     * @type {string}
     * @memberof FeeConfigs
     */
    'referralPerpsFee'?: string;
    /**
     * Earnings from subaffiliate perps
     * @type {string}
     * @memberof FeeConfigs
     */
    'subaffiliatePerpsEarnings'?: string;
    /**
     * Earnings from spot LP fees
     * @type {string}
     * @memberof FeeConfigs
     */
    'spotLPFee'?: string;
    /**
     * Earnings from referral spot LP fees
     * @type {string}
     * @memberof FeeConfigs
     */
    'referralSpotLPFee'?: string;
    /**
     * Earnings from referral lending rewards
     * @type {string}
     * @memberof FeeConfigs
     */
    'referralLendingRewards'?: string;
    /**
     * Cashback from perps fees
     * @type {string}
     * @memberof FeeConfigs
     */
    'perpsFeeCashback'?: string;
    /**
     * Revenue share percentage for perps
     * @type {string}
     * @memberof FeeConfigs
     */
    'perpsRevShare'?: string;
}

