/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AffiliateLeaderDashboard } from './affiliate-leader-dashboard';

/**
 * 
 * @export
 * @interface GetAffiliateLeaderDashboard200Response
 */
export interface GetAffiliateLeaderDashboard200Response {
    /**
     * 
     * @type {Array<AffiliateLeaderDashboard>}
     * @memberof GetAffiliateLeaderDashboard200Response
     */
    'data'?: Array<AffiliateLeaderDashboard>;
    /**
     * Total number of records
     * @type {number}
     * @memberof GetAffiliateLeaderDashboard200Response
     */
    'total'?: number;
    /**
     * The page size for pagination
     * @type {number}
     * @memberof GetAffiliateLeaderDashboard200Response
     */
    'limit'?: number;
    /**
     * The page number for pagination
     * @type {number}
     * @memberof GetAffiliateLeaderDashboard200Response
     */
    'page'?: number;
}

