/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MarketPriceUpdate
 */
export interface MarketPriceUpdate {
    /**
     * The symbol of the market.
     * @type {string}
     * @memberof MarketPriceUpdate
     */
    'symbol': string;
    /**
     * The price in scientific notation with 9 decimal places of precision.
     * @type {string}
     * @memberof MarketPriceUpdate
     */
    'priceE9': string;
    /**
     * 
     * @type {string}
     * @memberof MarketPriceUpdate
     */
    'source': MarketPriceUpdateSourceEnum;
    /**
     * The timestamp of the price update.
     * @type {number}
     * @memberof MarketPriceUpdate
     */
    'updatedAtMillis': number;
}

export const MarketPriceUpdateSourceEnum = {
    Market: 'Market'
} as const;

export type MarketPriceUpdateSourceEnum = typeof MarketPriceUpdateSourceEnum[keyof typeof MarketPriceUpdateSourceEnum];


