/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MarkPriceUpdate
 */
export interface MarkPriceUpdate {
    /**
     * The symbol of the market.
     * @type {string}
     * @memberof MarkPriceUpdate
     */
    'symbol': string;
    /**
     * The price in scientific notation with 9 decimal places of precision.
     * @type {string}
     * @memberof MarkPriceUpdate
     */
    'priceE9': string;
    /**
     * 
     * @type {string}
     * @memberof MarkPriceUpdate
     */
    'source': MarkPriceUpdateSourceEnum;
    /**
     * The timestamp of the price update.
     * @type {number}
     * @memberof MarkPriceUpdate
     */
    'updatedAtMillis': number;
}

export const MarkPriceUpdateSourceEnum = {
    Mark: 'Mark'
} as const;

export type MarkPriceUpdateSourceEnum = typeof MarkPriceUpdateSourceEnum[keyof typeof MarkPriceUpdateSourceEnum];


