/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The type of event communicated in the WebSocket message.
 * @export
 * @enum {string}
 */

export const MarketEventType = {
    RecentTradesUpdates: 'RecentTradesUpdates',
    TickerUpdate: 'TickerUpdate',
    TickerAllUpdate: 'TickerAllUpdate',
    OraclePriceUpdate: 'OraclePriceUpdate',
    MarkPriceUpdate: 'MarkPriceUpdate',
    MarketPriceUpdate: 'MarketPriceUpdate',
    CandlestickUpdate: 'CandlestickUpdate',
    OrderbookDiffDepthUpdate: 'OrderbookDiffDepthUpdate',
    OrderbookPartialDepthUpdate: 'OrderbookPartialDepthUpdate'
} as const;

export type MarketEventType = typeof MarketEventType[keyof typeof MarketEventType];



