/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CandlestickUpdate } from './candlestick-update';
// May contain unused imports in some cases
// @ts-ignore
import type { MarkPriceUpdate } from './mark-price-update';
// May contain unused imports in some cases
// @ts-ignore
import type { MarketPriceUpdate } from './market-price-update';
// May contain unused imports in some cases
// @ts-ignore
import type { OraclePriceUpdate } from './oracle-price-update';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderbookDiffDepthUpdate } from './orderbook-diff-depth-update';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderbookPartialDepthUpdate } from './orderbook-partial-depth-update';
// May contain unused imports in some cases
// @ts-ignore
import type { RecentTradesUpdates } from './recent-trades-updates';
// May contain unused imports in some cases
// @ts-ignore
import type { TickerAllUpdate } from './ticker-all-update';
// May contain unused imports in some cases
// @ts-ignore
import type { TickerUpdate } from './ticker-update';
// May contain unused imports in some cases
// @ts-ignore
import type { Trade } from './trade';

/**
 * @type MarketStreamMessagePayload
 * The payload of the message, which varies based on the event type.
 * @export
 */
export type MarketStreamMessagePayload = CandlestickUpdate | MarkPriceUpdate | MarketPriceUpdate | OraclePriceUpdate | OrderbookDiffDepthUpdate | OrderbookPartialDepthUpdate | RecentTradesUpdates | TickerAllUpdate | TickerUpdate;


