/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Map of social media usernames
 * @export
 * @interface OnboardAffiliateRequestSocialUserNames
 */
export interface OnboardAffiliateRequestSocialUserNames {
    /**
     * Twitter username
     * @type {string}
     * @memberof OnboardAffiliateRequestSocialUserNames
     */
    'twitter'?: string;
    /**
     * Instagram username
     * @type {string}
     * @memberof OnboardAffiliateRequestSocialUserNames
     */
    'instagram'?: string;
    /**
     * YouTube channel name
     * @type {string}
     * @memberof OnboardAffiliateRequestSocialUserNames
     */
    'youtube'?: string;
    /**
     * TikTok username
     * @type {string}
     * @memberof OnboardAffiliateRequestSocialUserNames
     */
    'tiktok'?: string;
}

