/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderSide } from './order-side';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderStatus } from './order-status';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderTimeInForce } from './order-time-in-force';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderType } from './order-type';
// May contain unused imports in some cases
// @ts-ignore
import type { SelfTradePreventionType } from './self-trade-prevention-type';

/**
 * 
 * @export
 * @interface OpenOrderResponse
 */
export interface OpenOrderResponse {
    /**
     * The Order Hash, which is the default way to uniquely identify an order in the system
     * @type {string}
     * @memberof OpenOrderResponse
     */
    'orderHash': string;
    /**
     * The Client Order ID, which is used a unique identifier for an order, provided by the client, in case of proprietary order management systems
     * @type {string}
     * @memberof OpenOrderResponse
     */
    'clientOrderId'?: string;
    /**
     * The market symbol
     * @type {string}
     * @memberof OpenOrderResponse
     */
    'symbol': string;
    /**
     * The account address of the order. May be an account user is authorized for.
     * @type {string}
     * @memberof OpenOrderResponse
     */
    'accountAddress': string;
    /**
     * The signer address of the order. May be an account user is authorized for.
     * @type {string}
     * @memberof OpenOrderResponse
     */
    'signerAddress': string;
    /**
     * The price in base e9 of the asset to be traded. Should always be a number
     * @type {string}
     * @memberof OpenOrderResponse
     */
    'priceE9': string;
    /**
     * The quantity in base e9 of the asset to be traded. Should always be a number
     * @type {string}
     * @memberof OpenOrderResponse
     */
    'quantityE9': string;
    /**
     * 
     * @type {OrderSide}
     * @memberof OpenOrderResponse
     */
    'side': OrderSide;
    /**
     * The leverage in base e9  of the order to be traded. Should always be a number
     * @type {string}
     * @memberof OpenOrderResponse
     */
    'leverageE9': string;
    /**
     * Is this order isolated or cross margin. Note market must be set to the same mode.
     * @type {boolean}
     * @memberof OpenOrderResponse
     */
    'isIsolated': boolean;
    /**
     * The random generated SALT. Should always be a number
     * @type {string}
     * @memberof OpenOrderResponse
     */
    'salt': string;
    /**
     * Unix timestamp in millis at which order will expire. Defaults to 1 month for LIMIT orders if not provided
     * @type {number}
     * @memberof OpenOrderResponse
     */
    'expiresAtMillis': number;
    /**
     * The timestamp in millis at which the request was signed
     * @type {number}
     * @memberof OpenOrderResponse
     */
    'signedAtMillis': number;
    /**
     * 
     * @type {OrderType}
     * @memberof OpenOrderResponse
     */
    'type': OrderType;
    /**
     * Is this order to only reduce a position? Default false
     * @type {boolean}
     * @memberof OpenOrderResponse
     */
    'reduceOnly': boolean;
    /**
     * If set to TRUE, the order can only be a maker order
     * @type {boolean}
     * @memberof OpenOrderResponse
     */
    'postOnly': boolean;
    /**
     * 
     * @type {OrderTimeInForce}
     * @memberof OpenOrderResponse
     */
    'timeInForce': OrderTimeInForce;
    /**
     * Trigger price in base e9 for stop orders. This should always be a number
     * @type {string}
     * @memberof OpenOrderResponse
     */
    'triggerPriceE9'?: string;
    /**
     * The quantity in base e9 of the asset currently filled. This should always be a number
     * @type {string}
     * @memberof OpenOrderResponse
     */
    'filledQuantityE9': string;
    /**
     * 
     * @type {OrderStatus}
     * @memberof OpenOrderResponse
     */
    'status': OrderStatus;
    /**
     * 
     * @type {SelfTradePreventionType}
     * @memberof OpenOrderResponse
     */
    'selfTradePreventionType': SelfTradePreventionType;
    /**
     * The timestamp in millis when the order was opened
     * @type {number}
     * @memberof OpenOrderResponse
     */
    'orderTimeAtMillis': number;
    /**
     * The timestamp in millis that this order was last updated (including status updates)
     * @type {number}
     * @memberof OpenOrderResponse
     */
    'updatedAtMillis': number;
}



