/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OraclePriceUpdate
 */
export interface OraclePriceUpdate {
    /**
     * The symbol of the market.
     * @type {string}
     * @memberof OraclePriceUpdate
     */
    'symbol': string;
    /**
     * The price in scientific notation with 9 decimal places of precision.
     * @type {string}
     * @memberof OraclePriceUpdate
     */
    'priceE9': string;
    /**
     * 
     * @type {string}
     * @memberof OraclePriceUpdate
     */
    'source': OraclePriceUpdateSourceEnum;
    /**
     * The timestamp of the price update.
     * @type {number}
     * @memberof OraclePriceUpdate
     */
    'updatedAtMillis': number;
}

export const OraclePriceUpdateSourceEnum = {
    Oracle: 'Oracle'
} as const;

export type OraclePriceUpdateSourceEnum = typeof OraclePriceUpdateSourceEnum[keyof typeof OraclePriceUpdateSourceEnum];


