/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrderbookDepthResponse
 */
export interface OrderbookDepthResponse {
    /**
     * Market symbol.
     * @type {string}
     * @memberof OrderbookDepthResponse
     */
    'symbol': string;
    /**
     * Count indicating the number of changes in orderbook state.
     * @type {number}
     * @memberof OrderbookDepthResponse
     */
    'lastUpdateId': number;
    /**
     * Timestamp at which the last change in orderbook state took place, in milliseconds.
     * @type {number}
     * @memberof OrderbookDepthResponse
     */
    'updatedAtMillis': number;
    /**
     * The time at which the orderbook server sent the response, in milliseconds.
     * @type {number}
     * @memberof OrderbookDepthResponse
     */
    'responseSentAtMillis': number;
    /**
     * The best bid price on orderbook at the moment (e9 format).
     * @type {string}
     * @memberof OrderbookDepthResponse
     */
    'bestBidPriceE9': string;
    /**
     * The best bid quantity on orderbook at the moment (e9 format).
     * @type {string}
     * @memberof OrderbookDepthResponse
     */
    'bestBidQuantityE9': string;
    /**
     * The best ask price on orderbook at the moment (e9 format).
     * @type {string}
     * @memberof OrderbookDepthResponse
     */
    'bestAskPriceE9': string;
    /**
     * The best ask quantity on orderbook at the moment (e9 format).
     * @type {string}
     * @memberof OrderbookDepthResponse
     */
    'bestAskQuantityE9': string;
    /**
     * Bids to be filled. Index 0 is price, index 1 is quantity at price bin. Prices are in e9 format.
     * @type {Array<Array<string>>}
     * @memberof OrderbookDepthResponse
     */
    'bidsE9': Array<Array<string>>;
    /**
     * Asks to be filled. Index 0 is price, index 1 is quantity at price bin. Prices are in e9 format.
     * @type {Array<Array<string>>}
     * @memberof OrderbookDepthResponse
     */
    'asksE9': Array<Array<string>>;
}

