/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Side of the order
 * @export
 * @enum {string}
 */

export const OrderSide = {
    Long: 'LONG',
    Short: 'SHORT',
    Unspecified: 'UNSPECIFIED'
} as const;

export type OrderSide = typeof OrderSide[keyof typeof OrderSide];



