/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The current status of the order.
 * @export
 * @enum {string}
 */

export const OrderStatus = {
    Standby: 'STANDBY',
    Open: 'OPEN',
    PartiallyFilledOpen: 'PARTIALLY_FILLED_OPEN',
    PartiallyFilledCanceled: 'PARTIALLY_FILLED_CANCELED',
    Filled: 'FILLED',
    Cancelled: 'CANCELLED',
    Expired: 'EXPIRED',
    PartiallyFilledExpired: 'PARTIALLY_FILLED_EXPIRED',
    Unspecified: 'UNSPECIFIED'
} as const;

export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];



