/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The reason for an order cancellation.
 * @export
 * @enum {string}
 */

export const OrderCancelReason = {
    Unspecified: 'UNSPECIFIED',
    InsufficientMargin: 'INSUFFICIENT_MARGIN',
    DuplicateOrder: 'DUPLICATE_ORDER',
    PostOnlyWouldTrade: 'POST_ONLY_WOULD_TRADE',
    InvalidSymbol: 'INVALID_SYMBOL',
    SignedAtTooOld: 'SIGNED_AT_TOO_OLD',
    OrderExpired: 'ORDER_EXPIRED',
    InvalidLeverage: 'INVALID_LEVERAGE',
    InvalidInput: 'INVALID_INPUT',
    PriceOutOfBound: 'PRICE_OUT_OF_BOUND',
    QuantityOutOfBound: 'QUANTITY_OUT_OF_BOUND',
    PriceOutOfTickSize: 'PRICE_OUT_OF_TICK_SIZE',
    QuantityOutOfStepSize: 'QUANTITY_OUT_OF_STEP_SIZE',
    ReduceOnlyWouldOpen: 'REDUCE_ONLY_WOULD_OPEN',
    TooManyOpenOrdersOnMarket: 'TOO_MANY_OPEN_ORDERS_ON_MARKET',
    UserCancelled: 'USER_CANCELLED',
    UserCancelledAllOnMarket: 'USER_CANCELLED_ALL_ON_MARKET',
    SelfTradePrevention: 'SELF_TRADE_PREVENTION',
    LeverageUpdate: 'LEVERAGE_UPDATE',
    AccountNotFound: 'ACCOUNT_NOT_FOUND',
    MarketNotTrading: 'MARKET_NOT_TRADING',
    InsufficientLiquidity: 'INSUFFICIENT_LIQUIDITY',
    PositionNotFound: 'POSITION_NOT_FOUND',
    LiquidationOutOfOrder: 'LIQUIDATION_OUT_OF_ORDER',
    AccountNotLiquidatable: 'ACCOUNT_NOT_LIQUIDATABLE',
    OrderNotReducingPosition: 'ORDER_NOT_REDUCING_POSITION',
    UserCancelledAllStandbyOnMarket: 'USER_CANCELLED_ALL_STANDBY_ON_MARKET',
    PositionExceedsMaxOpenInterest: 'POSITION_EXCEEDS_MAX_OPEN_INTEREST',
    AccountDeauthorized: 'ACCOUNT_DEAUTHORIZED'
} as const;

export type OrderCancelReason = typeof OrderCancelReason[keyof typeof OrderCancelReason];



