/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Indicates the type of subscription action.
 * @export
 * @enum {string}
 */

export const SubscriptionType = {
    Subscribe: 'Subscribe',
    Unsubscribe: 'Unsubscribe'
} as const;

export type SubscriptionType = typeof SubscriptionType[keyof typeof SubscriptionType];



