/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TradingFees
 */
export interface TradingFees {
    /**
     * The Account Maker Fee (e9 format).
     * @type {string}
     * @memberof TradingFees
     */
    'makerFeeE9': string;
    /**
     * The Account Taker Fee (e9 format).
     * @type {string}
     * @memberof TradingFees
     */
    'takerFeeE9': string;
    /**
     * Are the fees applied on the account?
     * @type {boolean}
     * @memberof TradingFees
     */
    'isApplied': boolean;
}

