/* tslint:disable */
/* eslint-disable */
/**
 * Bluefin API
 * Bluefin API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TransactionType } from './transaction-type';

/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * Transaction ID.
     * @type {string}
     * @memberof Transaction
     */
    'id': string;
    /**
     * Market address.
     * @type {string}
     * @memberof Transaction
     */
    'symbol'?: string;
    /**
     * 
     * @type {TransactionType}
     * @memberof Transaction
     */
    'type': TransactionType;
    /**
     * Amount in e9 format (positive or negative).
     * @type {string}
     * @memberof Transaction
     */
    'amountE9': string;
    /**
     * Transaction status (SUCCESS, REJECTED).
     * @type {string}
     * @memberof Transaction
     */
    'status'?: string;
    /**
     * Asset bank address.
     * @type {string}
     * @memberof Transaction
     */
    'assetSymbol': string;
    /**
     * Trade ID
     * @type {string}
     * @memberof Transaction
     */
    'tradeId'?: string;
    /**
     * Transaction timestamp in milliseconds since Unix epoch.
     * @type {number}
     * @memberof Transaction
     */
    'executedAtMillis': number;
}



